// <auto-generated />
namespace GWSApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class rates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rates));
        
        string IMigrationMetadata.Id
        {
            get { return "201504171857574_rates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
